### ISSUE TITLE
Simulation code for sm-fig1 and sm-fig2 are the wrong order

### ISSUE THREAD

**Issue by chenchen2015** [MacIver-Lab/Ergodic-Information-Harvesting#1]
### Description
`sm-fig1` and `sm-fig2` are the wrong order by mistake. The figure code has been fixed in 48de8ec but simulation code are pending fix. 

### TODO
- [x] Fix production figure code to link to the right dataset and data folder
- [x] Swap production code folder
- [x] Regenerate parameter json files to update output directory and file name prefix
- [x] Swap parameter folder
- [x] Verify the fix through simulation
