### ISSUE TITLE
[fig1, sm-fig2] Verify accordance with published

### ISSUE THREAD

**Issue by maciverlab** [MacIver-Lab/Ergodic-Information-Harvesting#5]
### Description
`fig1` EIH data under high SNR shows some minor mismatch with the production figure. Update the parameter to make sure it's consistent with production figure.

### TODO
- [x] Fix any parameter mismatch
- [x] Update parameter file
- [x] Update published dataset
- [x] Remake production figure 
- [x] Verify consistency between production figure and simulated figure at a different envionment

**Comment by chenchen2015** [comment]
Most recent simulation reveals some issues with setting parameter `tRes` which did not gets properly set from the simulation parameter json file. It has been fixed ([commit 2143ca6](https://github.com/chenchen2015/Ergodic-Information-Harvesting-Staging/commit/2c5bf9f5d9b65c4bf53ed7d36481ca0be22b7d13)) and new simulations are pending verification.

**Comment by chenchen2015** [comment]
Verified simulation parameter added in 0cd53d6

**Comment by chenchen2015** [comment]
### TODO
- [ ] Fix any parameter mismatch
- [ ] Update parameter file
- [ ] Update published dataset
- [ ] Remake production figure 
- [ ] Verify consistency between production figure and simulated figure at a different envionment

**Comment by chenchen2015** [comment]
sm-fig2 published dataset updated 5bb8868

**Comment by chenchen2015** [comment]
verified and synced with draft (rev. 10411) in 5820f92
