### ISSUE TITLE
[sm-fig1] Verify accordance with published

### ISSUE THREAD

**Issue by chenchen2015** [MacIver-Lab/Ergodic-Information-Harvesting#6]
### Description
The simulation of `sm-fig1` currently has not yet been verified. Previous simulation on the new centralized code has missing trials whose data did not get saved.

The simulated data has not yet been tested against production figure.

### TODO
- [x] Fix simulation code order in #1 
- [x] Look into`sm-fig1` simulation and identify any issues, make sure it runs with all of the data saved
- [x] Verify the data processing code
- [x] Verify the production figure code

**Comment by chenchen2015** [comment]
### TODO
Make new plot of percentage of time not moving for Infotaxis

**Comment by chenchen2015** [comment]
Final verification pending
