### ISSUE TITLE
[sm-fig4] Verify simulation and figure code accordance with published

### ISSUE THREAD

**Issue by chenchen2015** [MacIver-Lab/Ergodic-Information-Harvesting#7]
### Description
`sm-fig4` simulation currently has minor issues with the new centralized code pending fix. This is most likely during the process of MATLAB calling Python script to run trajectory simulation.

Once fixed, verify the simulated dataset to make sure they are consistent with the published figure.

### TODO
- [x] Identify and fix the bug causing number of simulation jobs to be less than actually submitted
- [x] Fix the simulation bug during the python trajectory simulation (`EIH-API`)
- [x] Verify simulated dataset and fix any parameter mismatch issue
- [x] Plug dataset into production figure code to verify figure reproduction

**Comment by chenchen2015** [comment]
New simulation result from `SMFig4Sim` seems to have issues with computing ergodicity

**Comment by chenchen2015** [comment]
@maciverlab  has found previously that the number of simulated jobs is wrong and less than what is needed. The bug causing this was found in the `SimulationMain.py` file which used the wrong parameter to terminate the main loop for submitting multi-threaded jobs.

The patch has been implemented in the staging repo at [commit c6ef878](https://github.com/chenchen2015/Ergodic-Information-Harvesting-Staging/commit/7b01b69be734353b505e6bdb155bbf2ae5a5b715) and will be merged to the main repo once verified.
