### ISSUE TITLE
[fig2] Fix data mismatch

### ISSUE THREAD

**Issue by chenchen2015** [MacIver-Lab/Ergodic-Information-Harvesting#9]
### Description
Simulation parameter for rat trajectory under strong signal condition is different with production figure, try to identify the issue and update the parameter to make sure it's consistent.

### TODO
- [x] Identify issue which caused simulation parameter mismatch
- [x] Patch the simulation parameter to address the identified issue
- [x] Proceed with simulation to verify updated parameter
- [x] Update production figure used in the paper
- [x] Finalize simulated figure and update production figure to make sure they are consistent

**Comment by chenchen2015** [comment]
Verified simulation parameter added in 0cd53d6

**Comment by chenchen2015** [comment]
### TODO
- [ ] Identify issue which caused simulation parameter mismatch
- [ ] Patch the simulation parameter to address the identified issue
- [ ] Proceed with simulation to verify updated parameter
- [ ] Update production figure used in the paper
- [ ] Finalize simulated figure and update production figure to make sure they are consistent

**Comment by chenchen2015** [comment]
verified and synced with draft (rev. 10411) in 5bb8868
